DROP SCHEMA PUBLIC CASCADE;
CREATE SCHEMA PUBLIC;

CREATE TABLE account (
  id BIGSERIAL PRIMARY KEY,
  license CHAR(36) UNIQUE NOT NULL,
  email VARCHAR NOT NULL,
  pin CHAR(7) NOT NULL,
  activated VARCHAR(10) NOT NULL
);

CREATE TABLE house (
  id BIGSERIAL PRIMARY KEY,
  account_id BIGINT REFERENCES account(id),
  typeof VARCHAR NOT NULL,
  location VARCHAR NOT NULL,
  built VARCHAR NOT NULL
);

CREATE TABLE foundation (
  id BIGSERIAL PRIMARY KEY,
  house_id BIGINT REFERENCES house(id),
  typeof VARCHAR NOT NULL,
  built VARCHAR NOT NULL
);