package objektwerks

import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.macros.*

object Serializer:
  given JsonValueCodec[Entity] = JsonCodecMaker.make[Entity](CodecMakerConfig.withDiscriminatorFieldName(None))
  given JsonValueCodec[Account] = JsonCodecMaker.make[Account]
  given JsonValueCodec[House] = JsonCodecMaker.make[House]
  given JsonValueCodec[Foundation] = JsonCodecMaker.make[Foundation]
  given JsonValueCodec[Frame] = JsonCodecMaker.make[Frame]
  given JsonValueCodec[Attic] = JsonCodecMaker.make[Attic]
  given JsonValueCodec[Insulation] = JsonCodecMaker.make[Insulation]
  given JsonValueCodec[Ductwork] = JsonCodecMaker.make[Ductwork]
  given JsonValueCodec[Ventilation] = JsonCodecMaker.make[Ventilation]
  given JsonValueCodec[Roof] = JsonCodecMaker.make[Roof]
  given JsonValueCodec[Chimney] = JsonCodecMaker.make[Chimney]
  given JsonValueCodec[Balcony] = JsonCodecMaker.make[Balcony]
  given JsonValueCodec[Drywall] = JsonCodecMaker.make[Drywall]
  given JsonValueCodec[Room] = JsonCodecMaker.make[Room]
  given JsonValueCodec[Driveway] = JsonCodecMaker.make[Driveway]
  given JsonValueCodec[Garage] = JsonCodecMaker.make[Garage]
  given JsonValueCodec[Siding] = JsonCodecMaker.make[Siding]
  given JsonValueCodec[Gutter] = JsonCodecMaker.make[Gutter]
  given JsonValueCodec[Soffit] = JsonCodecMaker.make[Soffit]
  given JsonValueCodec[Window] = JsonCodecMaker.make[Window]
  given JsonValueCodec[Door] = JsonCodecMaker.make[Door]
  given JsonValueCodec[Plumbing] = JsonCodecMaker.make[Plumbing]
  given JsonValueCodec[Electrical] = JsonCodecMaker.make[Electrical]
  given JsonValueCodec[Fusebox] = JsonCodecMaker.make[Fusebox]
  given JsonValueCodec[Alarm] = JsonCodecMaker.make[Alarm]
  given JsonValueCodec[Heater] = JsonCodecMaker.make[Heater]
  given JsonValueCodec[AirConditioner] = JsonCodecMaker.make[AirConditioner]
  given JsonValueCodec[Floor] = JsonCodecMaker.make[Floor]
  given JsonValueCodec[Lighting] = JsonCodecMaker.make[Lighting]
  given JsonValueCodec[Sewage] = JsonCodecMaker.make[Sewage]
  given JsonValueCodec[Well] = JsonCodecMaker.make[Well]
  given JsonValueCodec[Water] = JsonCodecMaker.make[Water]
  given JsonValueCodec[WaterHeater] = JsonCodecMaker.make[WaterHeater]
  given JsonValueCodec[Lawn] = JsonCodecMaker.make[Lawn]
  given JsonValueCodec[Garden] = JsonCodecMaker.make[Garden]
  given JsonValueCodec[Sprinkler] = JsonCodecMaker.make[Sprinkler]
  given JsonValueCodec[Shed] = JsonCodecMaker.make[Shed]
  given JsonValueCodec[SolarPanel] = JsonCodecMaker.make[SolarPanel]
  given JsonValueCodec[Porch] = JsonCodecMaker.make[Porch]
  given JsonValueCodec[Patio] = JsonCodecMaker.make[Patio]
  given JsonValueCodec[Pool] = JsonCodecMaker.make[Pool]
  given JsonValueCodec[Dock] = JsonCodecMaker.make[Dock]
